import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const fingerPaint = localFont({
  src: [
    {
      path: "../../public/fonts/FingerPaint-Regular.ttf",
      weight: "400",
    },
  ],
});

export const metadata: Metadata = {
  title: "Base Days",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fingerPaint.className} antialiased`}>{children}</body>
    </html>
  );
}
